
spring.application.name=hospital-api
# New Railway Cloud Database Connection
spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:11161/railway?useSSL=true
spring.datasource.username=root
spring.datasource.password=XLbEqOcUjUBwXfLskEGdYKdMOBdsRxgv
>>>>>>> c17efdac2aa6dc11c58b1d7c4d060b2ec45cf061
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver